pipeline {
    
    agent { 
        node{
            label "dev"
            
        }
    }
    environment {
       DOCKER_IMAGE = "kushagrag99/notes-app:v1.${BUILD_NUMBER}" 
       REGISTRY_CREDENTIALS = credentials('docker-cred')
    }
    
    stages{
        stage("Checkout Code"){
            steps{
                git branch: 'main', url: 'https://github.com/kushagra-g9/devops-observability.git'
                
            }
        }
        stage("Build Docker Image"){
            steps{
                dir('notesapp')
                sh "docker build -t ${DOCKER_IMAGE} ."
            }
        }
       stage('Push Docker Image') {
      steps {
        script {
          def dockerImage = docker.image("${DOCKER_IMAGE}")
          docker.withRegistry('https://index.docker.io/v1/', "docker-cred") {
            dockerImage.push()
          }
        }
      }
    }
        
        stage("Deploy"){
            steps{
                sh "docker-compose up -d"
            }
        }
    }
}


